### PR TITLE
Bkg 2d stat

### PR DESCRIPTION
**Pull request by benjaminkreis**
This PR contains the code to do the background estimate with 2D mistag rates and correct statistical uncertainty.  

We will need to resolve some conflicts here, but just getting it started

### CODE REVIEW

**Comment by benjaminkreis** [comment]
Okay, I was able to fix the minor conflicts.  I expect there will have to be a few more changes to adapt to recent merges.

I will go through this once before asking for review.

As a note mostly to myself right now, this is the order to run:
1. Run analyzer and hadd 
2. plotters/plot_added(false)
3. plotters/plot_eff
4. Run analyzer with new analyzer/feff_ZH.root and hadd
5. plotters/plot_added(true)
6. plotters/plot_bkgest

**Comment by benjaminkreis** [comment]
ready for review!

**Comment by tmrhombus** [comment]
ok thanks, I'm looking at it - just to make sure, the first time I run (step 1 above), am I correct in thinking that I should have doBkgEst=false (analyzer_loop.C#L41)

**Review by tmrhombus — COMMENTED** [review]
for plot_added.C , should we also include VG and (gg)ZH to the samples L122 ?

**Comment by benjaminkreis** [comment]
Regarding doBkgEst in analyzer_loop, I've actually just been running with it always true and just ignoring the background estimate output the first time.  The one thing about that is that you need to have the root file with mistag rates there in the analyzer directory.  The other option is to run with doBkgEst false the first time.  I haven't tried this in a while, but it should work.

For plot_added, yeah I suppose at least VG is not completely negligible.  I'll add that now.  Thanks!

**Comment by benjaminkreis** [comment]
also updated lepton pT and Eta cuts

**Pull request merged**
