### PR TITLE
Fix for sl7

### PR DESCRIPTION
**Pull request by benjaminkreis**
running but has issues -- histograms losing names and scale function seg faulting

### CODE REVIEW

**Comment by benjaminkreis** [comment]
I ran this on condor and spot checked the output.  It looks okay, so I say it's ready to be reviewed and merged.

I couldn't get the delete functions to work, but we can cross that bridge when we come to it.  It runs ok without using the deletes.

**Comment by ddiaz006** [comment]
Ok,

First try running this I get
`Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3011] No servers are available to read the file.`
which seems to show up at this line in analyser_loop.C
`Long64_t ientry = LoadTree(jentry);`


...Still investigating

**Comment by benjaminkreis** [comment]
This is an EOS thing.  We had some issues at FNAL overnight.  Try again please!

**Comment by ddiaz006** [comment]
I have run the code and things look mostly fine. I can merge this now or we can add one update. Currently we are making a bunch of unfilled root files corresponding to the phase space selections we no longer care about, like OneMuDY/Ele... Tom had a "hack" in loop.C to only write out the ones we want https://github.com/DisplacedHiggs/LLDJstandalones/blob/master/analyzers/analyzer_loop.C#L474

So there are two options; remove the hack from above and fill/write every thing or stop the creation of the extra root files.

**Pull request merged**
