### PR TITLE
L1PF/TTOC/Efficiency tweaks

### PR DESCRIPTION
**Pull request by ddiaz006**
- In this pull request, the major additions are my inputs of the TTOC and L1PF plots to the analyzer. In addition I added some switches to make submitting jobs a little faster by cutting out some plots that we do not use often. 

- In analyzer_config.h there are switches now for turning off and on the TTOC plots as well as the jet multiplicity plots other than all jets.

- I updated plotting scripts mostly used by me for the TTOC's and the L1PF test

- I have run through this PR from submitjobs-hadd-plotting and things look fine. This was all done with the systematics bins turned on.

- Note that the tagging variable binning is at 500(I would like to make the switching of this automatic in the future form 500to30<forSystematicsOff> and 30to500<forSystematicsOn>). Please also change the switches in analyzer_config.h depending on your preferences.

### CODE REVIEW

**Comment by tmrhombus** [comment]
I'm not sure if I really understand the logic behind the complications you put in for doTTOC - is this because you change the selvec? 
also `for( unsigned int k=(jetmultnames.size()-1); k<jetmultnames.size(); ++k){` probably isn't necessary

**Comment by tmrhombus** [comment]
... probably isn't necessary but it did make me smile

**Comment by ddiaz006** [comment]
@tmrhombus the reason for the redefinition of the the iteration variable is not for the TTOC switch it is for the jetMultiplicity switch. In this case if we turn off jet multiplicity we will only initialize/write/fill histograms for the “allJets” jet multiplicity bin. I think without it we will get a bunch of empty histograms in the root file.

**Comment by tmrhombus** [comment]
right, about the iteration variable, I get that and was just saying that instead of doing an "iteration" of one step with
```
     else{
     for( unsigned int k=(jetmultnames.size()-1); k<jetmultnames.size(); ++k){
      fillSelectedJetHistograms( fullweight, i, k );
     }  }
```
you could just have
```
     else{
      fillSelectedJetHistograms( fullweight, i, jetmultnames.size()-1 );
      }
```
that's what I thought was kind of a funny little joke

And for TTOC, what I'm talking about is the fact that you have `static const Bool_t TTOC = kTRUE;` and 
```
Bool_t analyzer_config::doTTOC(){
  return TTOC;
}
```
to get called in main.C - it seems at first glance like this is all overly complicated

**Comment by ddiaz006** [comment]
Hi Tom, 
Overly Complicated? Do you have a suggestion to make this less complicated or do you suggest not implementing these changes? I did not take the approach you have above of 
```
     else{
      fillSelectedJetHistograms( fullweight, i, jetmultnames.size()-1 );
      }
```
because, then I would be repeating all of the lines in the for loop. https://github.com/ddiaz006/LLDJstandalones/blob/master/analyzers/analyzer_histograms.C#L904 . Rewriting the iteration variable preserves the ability to run for all jetbins as well as only the AllJets bin only. I was trying to make it so that unless someone changes the switch in config.h, it would run as normal without really noticing these changes. And ya, I agree that the function doTTOC is a bit over the top, but it was the quickest way I could think of being able to talk to main.C from one of the analyzer programs, if you have a different method I'm all ears.

**Comment by ddiaz006** [comment]
Accidentally closed this, reopening

**Comment by tmrhombus** [comment]
Of course I think we should implement these changes!

I think there still must have been some miscommunication because the lines I copy/pasted above aren't in `analyzer_histograms`. I like what you did in `histograms.C#L904` and think that's a clever way to put in the switch. I was talking about https://github.com/ddiaz006/LLDJstandalones/blob/master/analyzers/analyzer_loop.C#L366L369 but it really doesn't matter and if you want to keep the "loop" that's fine with me.

Checking things a bit further, I also see that https://github.com/ddiaz006/LLDJstandalones/blob/master/analyzers/analyzer_selections.C#L297L305 seems fishy . Does this seem right? 
```
Bool_t analyzer_selections::askPassMuEG()
{
 Bool_t doespass = kFALSE;
 if(muon_list.size()>0 && electron_list.size()>0){
  if(TTOC){
   doespass = kTRUE;
  } // if(TTOC)
  else{
   if( isMC ){
    doespass =  (Bool_t)( (AOD_HLT_Mu12Ele23_DZ > 0) || (AOD_HLT_Mu23Ele12_DZ > 0) );
   } // if( isMC )
   else{
    if(run>=273158 && run<=278272){
     doespass =  (Bool_t)( (AOD_HLT_Mu8Ele23 > 0) || (AOD_HLT_Mu23Ele12 > 0) );
    }
    else if(run>=278273 && run<=284044){
     doespass = (Bool_t)( (AOD_HLT_Mu12Ele23_DZ > 0) || (AOD_HLT_Mu23Ele12_DZ > 0) );
    }
   } // if( !isMC )
  } // if(!TTOC)
 } // if(muon_list.size()>0 && electron_list.size()>0)
 return doespass;
}
``` 

And then for the TTOC part, I think the complications come from the fact that TTOC is logically kind of it's own independent thing from the main analyzer but I agree with the idea of reusing the infrastructure we already have built. As of now there are kind of two places where stuff is being set, `config.C` and as flags in `main.C` so my thought here on a cleaner approach would be to put TTOC all the way at the top level.

**Comment by ddiaz006** [comment]
Ah, I see. Ya, I think I came up for the loop solution in histograms.C and then copied it in loop.C, but ya the other way probably makes more sense for analyzer_loop.C, I can change this before it is merged. You're right about the askPassMuEG() function, it should be if(TTOC) doesPass=kTRUE.

**Comment by ddiaz006** [comment]
Should be good to go now

**Comment by tmrhombus** [comment]
Those lines in analyzer_selections still looked fishy to me so I fixed them and then added the systematics back in to our default configuration and made a new PR from my area after merging in @ddiaz006 's changes. I guess this probably doesn't have much of an effect, but to be totally clear on what I was talking about in those lines I was pointing to, this code will overwrite what we want doespass in MC if for whatever reason the run number falls into one of those ranges and I don't think we want that potential effect

```
   if( isMC ){
    doespass =  (Bool_t)( (AOD_HLT_Mu12Ele23_DZ > 0) || (AOD_HLT_Mu23Ele12_DZ > 0) );
   }
   if(run>=273158 && run<=278272){
    doespass =  (Bool_t)( (AOD_HLT_Mu8Ele23 > 0) || (AOD_HLT_Mu23Ele12 > 0) );
   }
   else if(run>=278273 && run<=284044){
    doespass = (Bool_t)( (AOD_HLT_Mu12Ele23_DZ > 0) || (AOD_HLT_Mu23Ele12_DZ > 0) );
}```

**Comment by ddiaz006** [comment]
Ok, I think either way is fine since run number is 1 for MC it wouldn't fall into the other loops until we are running on data. But might as well be explicit.

**Comment by benjaminkreis** [comment]
Closing this because we have PR #102

**Pull request closed without merging**
