### PR TITLE
Add AOD trigger info

### PR DESCRIPTION
**Pull request by benjaminkreis**
Accessing the AOD trigger info required some pretty substantial changes with respect to the MiniAOD code.  I based this one the Rutgers framework I was using.

Once we have the trigger name, accept result, and prescale, the code is basically the same as the MiniAOD code.  I did not yet try to understand how this is encoded into the branches with the bit shifting etc.  It's just a copy of the MiniAOD code at that point with a couple of trivial bug fixes (see Slack).

I was able to run on MC and see some nonzero values in the branches.  I put in what I think I need to run on data as well, but it's not running due to what looks like an electron problem (trying to get gen info from data?):
```
----- Begin Fatal Exception 06-Feb-2018 18:10:15 CST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 278406 lumi: 657 event: 1080755826
   [1] Running path 'p'
   [2] Calling event method for module MCMatcher/'electronMatch'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::GenParticle>
Looking for module label: genParticles
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

I also made a couple of unrelated changes
- comment out unused variables in AOD jet code to clean up warnings
- added some lines to the run_data_80XAOD.py for muons.  apparently I only ran MC so far.

### CODE REVIEW

**Comment by tmrhombus** [comment]
Hi, I'm sorry for taking to long to respond - I'm trying to move away from so much HCAL, and it is happening, I swear. Anyways, this gen match issue doesn't seem to be just an electon issue, it's just that electons are the first to be called in the sequence. For the students, I'll try to go through my full debugging process here because this is also the kind of thing that is worth knowing how to do.

Looking at our magic import statement in runWhateverAOD.py

process.load('PhysicsTools.PatAlgos.patSequences_cff')

this pulls from 

https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_26_patch1/PhysicsTools/PatAlgos/python/patSequences_cff.py

which, as a side note seems to imply that maybe the right sequence for us to use isn't 

    process.particleFlowPtrs *
    process.patCandidates *
    process.selectedPatCandidates 

(which was just taken from the Rutgers framework) and should actually maybe just be

patDefaultSequence = cms.Sequence(
    patCandidates *
    selectedPatCandidates *
    cleanPatCandidates *
    countPatCandidates
)

But blindly switching to this doesn't fix the problem. Tracing a bit further, the problem appears in the patCandidates sequence which you can find in an import statement in patSequences_cff.py to be located here:

https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_26_patch1/PhysicsTools/PatAlgos/python/producersLayer1/patCandidates_cff.py

This is where you can see that we fail on the electrons just because they are the first to be pulled in. Checking out the electronProducer and the sequence makePatElectrons in

https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_26_patch1/PhysicsTools/PatAlgos/python/producersLayer1/electronProducer_cff.py

the offending line is associated with the electronMatch producer. The _cff.py pulls its default values from the _cfi.py, ie.

https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_26_patch1/PhysicsTools/PatAlgos/python/producersLayer1/electronProducer_cfi.py

and here we can see that there are some default settings:

addGenMatch      = cms.bool(True),
embedGenMatch    = cms.bool(True),


So this seems to be the problem, it also appears in these producers things like

electronSource = cms.InputTag("gedGsfElectrons"),
useParticleFlow = cms.bool( False ),

muonSource      = cms.InputTag("muons"),
useParticleFlow = cms.bool( False ),

which might(?) contradict our previous statement that PF is the right way to go. Either way, I'm continuing to look in to this, but other thoughts are always welcome.

**Comment by benjaminkreis** [comment]
Thanks for digging into this @tmrhombus!  Maybe I'm using runOnData incorrectly?

**Comment by benjaminkreis** [comment]
I'm really mystified about why runOnData is not working!  It should turn off those lines you found:

https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/PhysicsTools/PatAlgos/python/tools/coreTools.py#L171-L172

**Comment by benjaminkreis** [comment]
One potential clue is that if I remove
```
    process.particleFlowPtrs *                                                                                                             
    process.patCandidates *                                                                                                                
    process.selectedPatCandidates *  
```
from run_data_80XAOD.py , it runs without errors.

However if I remove those lines from run_mc_80XAOD.py, it tells me it can't find the AOD muon collection I wanted (which IIRC was why I added those lines).

**Comment by tmrhombus** [comment]
Yea, I'm also confused by this. What you say in your hint also agrees with my observation that the problem seems to be in the patCandidates sequence, all the way down the line when it calls the MCMatch producer for things like electrons/muons/etc. And I also agree that runOnData should solve this via the lines you point to. I was wondering if this might be an ordering issue, where our values of False get overwritten to True later, but I also can't see where that would be happening. I tried adding lines directly into our top level config like 

process.patElectrons.addGenMatch   = cms.bool(False)
process.patElectrons.embedGenMatch = cms.bool(False)
process.electronMatch.addGenMatch   = cms.bool(False)
process.electronMatch.embedGenMatch = cms.bool(False)

but this doesn't seem to have an effect. Neither does what I would think should provoke a new failure - adding the lines

process.patElectrons.electronSource = cms.InputTag("xxxxx")
process.electronMatch.electronSource = cms.InputTag("xxxxx")

So the problem seems to be that these lines (and the preferred runOnData) are for some reason not communicating with the pat sequence.

**Comment by benjaminkreis** [comment]
So those lines are actually setting those parameters to false.  If I do this:
```
print process.patElectrons.addGenMatch
print process.patElectrons.embedGenMatch

runOnData( process ,names=['Photons', 'Electrons','Muons', 'Taus', 'METs', 'PFAll', 'PFElectrons','PFTaus','PFMuons'] )
removeMCMatching(process, names=['Photons', 'Electrons','Muons', 'Taus', 'METs', 'PFAll', 'PFElectrons','PFTaus','PFMuons'], outputModules=\
[])#this seems to be doing the same thing as runOnData                                                                                      
                                                                                                                 
print process.patElectrons.addGenMatch
print process.patElectrons.embedGenMatch

process.p = cms.Path(
    process.particleFlowPtrs *
    process.patCandidates *
    process.selectedPatCandidates *
    process.lldjNtuple
    )

print process.patElectrons.addGenMatch
print process.patElectrons.embedGenMatch

```

I get:
```
cms.bool(True)
cms.bool(True)
******************* RunOnData *******************
************** MC dependence removal ************
removing MC dependencies for photons
removing MC dependencies for electrons
removing MC dependencies for muons
removing MC dependencies for taus
adding L2L3Residual JEC for: patJetCorrFactors
************** MC dependence removal ************
removing MC dependencies for photons
removing MC dependencies for electrons
removing MC dependencies for muons
removing MC dependencies for taus
cms.bool(False)
cms.bool(False)
cms.bool(False)
cms.bool(False)
```

So there must be something else we need to set?

**Comment by benjaminkreis** [comment]
Still digging...

I get rid of the error with:
```
process.patCandidates.remove(process.electronMatch)
```
but the question is how to do this without hacks.

**Comment by benjaminkreis** [comment]
But... the rutgers framework keeps electronMatch and it still runs ok...

**Comment by benjaminkreis** [comment]
no, nevermind it's not in rutgers.  it's in a sequence but not the path

**Comment by benjaminkreis** [comment]
Okay! I think I finally have some progress.  Stuff works if I remove 
```
    process.particleFlowPtrs *
    process.patCandidates *
    process.selectedPatCandidates *
```
and allow unscheduled mode.  I added this stuff to make PAT muons, but it seems to be overkill.  If I use unscheduled mode, it runs what it needs and doesn't get into the matching.

Sorry for all the messages.  Just want to keep this thread up to date in case @tmrhombus and I overlap.

**Comment by benjaminkreis** [comment]
Python configs are updated.  This should run on MC and data and produce non trivial output for AOD muons and triggers, so I claim this is ready to merge.  Let me know what you think, @tmrhombus!

**Comment by tmrhombus** [comment]
thanks ben! I'll merge it and then do the more thorough check. Then by the end of today I will hopefully have this integrated into the stuff I've been working on

**Review by tmrhombus — COMMENTED** [review]
I'm slightly skeptical about  allowUnscheduled, but that's mostly just because I don't really understand all of its implications.

**Pull request merged**
